# Листок № 1. СЛАУ, матрицы, квадратичные формы — решения


## 1.1. СЛАУ (3 уравнения, 4 неизвестных)

$$\begin{cases} x_1+5x_2-2x_3=-7\\ -3x_1+x_2+9x_3-5x_4=9\\ 4x_1-8x_2-x_3+7x_4=0 \end{cases}$$

**Метод:** строим расширенную матрицу $(A|b)$ и приводим её к rref (`Matrix.rref()`). Столбцы без ведущей единицы — свободные переменные, через них выражаем остальные.

In [1]:
from sympy import Matrix, init_printing  # SymPy даёт точные вычисления с матрицами и дробями без округления
init_printing()  # включаем красивый вывод формул

A = Matrix([[1,5,-2,0],[-3,1,9,-5],[4,-8,-1,7]])  # матрица коэффициентов системы
b = Matrix([-7,9,0])  # столбец свободных членов

Ab = A.row_join(b)  # собираем расширенную матрицу (A|b), пришивая b справа

rref, pivots = Ab.rref()  # методом Гаусса-Жордана приводим (A|b) к ступенчатому виду

print("Ведущие (базисные) столбцы:", pivots)  # pivots — номера столбцов с базисными переменными
rref  # остальные переменные свободные — через них выражается общее решение

Ведущие (базисные) столбцы: (0, 1, 2)


⎡1  0  0  8/7   -11/7⎤
⎢                    ⎥
⎢0  1  0  -2/7  -6/7 ⎥
⎢                    ⎥
⎣0  0  1  -1/7   4/7 ⎦

**Ответ:** пивоты в столбцах $x_1,x_2,x_3$, $x_4=t$ — свободная переменная:
$$x_1=-\tfrac{11}{7}-\tfrac{8}{7}t,\quad x_2=-\tfrac{6}{7}+\tfrac{2}{7}t,\quad x_3=\tfrac{4}{7}+\tfrac{1}{7}t,\quad x_4=t,\ \ t\in\mathbb{R}$$

## 1.2. СЛАУ (3 уравнения, 5 неизвестных)

$$\begin{cases}5x_1-x_2+5x_3+9x_4-2x_5=-3\\3x_1+6x_3+9x_4-x_5=4\\2x_1+4x_3+6x_4-x_5=0\end{cases}$$

**Метод:** то же самое — rref расширенной матрицы, затем выражаем базисные переменные через свободные $x_3,x_4$.

In [2]:
from sympy import Matrix, init_printing  # SymPy для точных символьных вычислений
init_printing()  # включаем красивый вывод формул

A = Matrix([[5,-1,5,9,-2],[3,0,6,9,-1],[2,0,4,6,-1]])  # матрица коэффициентов (3 уравнения, 5 неизвестных)
b = Matrix([-3,4,0])  # столбец свободных членов

Ab = A.row_join(b)  # собираем расширенную матрицу (A|b)

rref, pivots = Ab.rref()  # приводим к ступенчатому виду методом Гаусса-Жордана

print("Ведущие (базисные) столбцы:", pivots)  # определяем, какие переменные базисные, а какие свободные
rref

Ведущие (базисные) столбцы: (0, 1, 4)


⎡1  0  2  3  0  4⎤
⎢                ⎥
⎢0  1  5  6  0  7⎥
⎢                ⎥
⎣0  0  0  0  1  8⎦

**Ответ:** а) $\mathrm{rref}(A|b)=\begin{pmatrix}1&0&2&3&0&4\\0&1&5&6&0&7\\0&0&0&0&1&8\end{pmatrix}$;
б) $x=(4-2x_3-3x_4;\ 7-5x_3-6x_4;\ x_3;\ x_4;\ 8)$.

## 1.3. Выразить $y$ как функцию от $x$

$$\begin{cases}32x+97y+90z+48u=47\\35x+84y+91z+54u=40\\17x+18y+21z+13u=37\end{cases}$$

**Пояснение:** система имеет 3 уравнения и 4 неизвестных, ранг матрицы коэффициентов равен 3 ⇒ решение — прямая (одномерное аффинное множество), которую можно параметризовать переменной $x$. Решаем систему относительно $y,z,u$, выражая их через $x$ (`solve(..., [y,z,u])`), откуда сразу видно, что $y$ линейно зависит от $x$.

In [3]:
from sympy import symbols, Eq, solve  # SymPy для точного аналитического решения

x, y, z, u = symbols('x y z u')  # объявляем все четыре неизвестных как символы

eqs = [Eq(32*x + 97*y + 90*z + 48*u, 47),
       Eq(35*x + 84*y + 91*z + 54*u, 40),
       Eq(17*x + 18*y + 21*z + 13*u, 37)]  # записываем исходную систему уравнений

sol = solve(eqs, [y, z, u], dict=True)[0]  # решаем систему относительно y, z, u, оставляя x свободным параметром
sol  # получаем y, z, u как линейные функции от x

**Ответ:** $y=14027-4262x$, то есть **1)** $a=14027$; **2)** $b=-4262$.

## 1.4. Умножение и сложение матриц

**Метод:** прямое вычисление $M_1\cdot M_2 + M_3$ в sympy.

In [4]:
from sympy import Matrix  # у SymPy оператор * — матричное умножение, + — поэлементное сложение

M1 = Matrix([[3,0,2],[0,1,3],[2,2,0],[0,1,0]])  # первая матрица (4x3)
M2 = Matrix([[1,2,-1,2],[-2,-1,1,2],[2,1,1,2]])  # вторая матрица (3x4)
M3 = Matrix([[0,-4,6,1],[2,2,-5,-2],[2,-2,6,4],[1,3,0,1]])  # третья матрица (4x4) — для сложения

result = M1*M2 + M3  # сначала перемножаем M1 и M2 (получаем 4x4), затем прибавляем M3
result

⎡7   4  5   11⎤
⎢             ⎥
⎢6   4  -1  6 ⎥
⎢             ⎥
⎢0   0  6   12⎥
⎢             ⎥
⎣-1  2  1   3 ⎦

**Ответ:**
$$M_1 M_2+M_3=\begin{pmatrix}7&4&5&11\\6&4&-1&6\\0&0&6&12\\-1&2&1&3\end{pmatrix}$$

## 1.5. Определители порядка $n$

а) $a_{ij}=\min(i,j)$; б) $a_{ij}=\max(i,j)$; в) $a_{ij}=|i-j|$.

**Метод:** вычисляем определители символьно для $n=1,\dots,7$, ищем закономерность в получившейся последовательности чисел.

In [5]:
from sympy import Matrix  # SymPy считает определитель точно, без ошибок округления

for n in range(1, 8):  # перебираем порядок матрицы n от 1 до 7, чтобы увидеть закономерность
    Amin  = Matrix(n, n, lambda i, j: min(i+1, j+1))  # строим матрицу с элементами a_ij = min(i,j)
    Amax  = Matrix(n, n, lambda i, j: max(i+1, j+1))  # строим матрицу с элементами a_ij = max(i,j)
    Adiff = Matrix(n, n, lambda i, j: abs((i+1) - (j+1)))  # строим матрицу с элементами a_ij = |i-j|
    print(f"n={n}:  min-det={Amin.det()}   max-det={Amax.det()}   diff-det={Adiff.det()}")  # считаем и печатаем все три определителя

n=1:  min-det=1   max-det=1   diff-det=0
n=2:  min-det=1   max-det=-2   diff-det=-1
n=3:  min-det=1   max-det=3   diff-det=4
n=4:  min-det=1   max-det=-4   diff-det=-12
n=5:  min-det=1   max-det=5   diff-det=32
n=6:  min-det=1   max-det=-6   diff-det=-80
n=7:  min-det=1   max-det=7   diff-det=192


**Закономерность и ответ:**
- а) $\det=1$ для любого $n$ (в rref у такой матрицы все пивоты равны 1, что легко проверяется приведением);
- б) $\det=(-1)^{n-1}\,n$;
- в) при $n\ge 2$: $\det=(-1)^{n-1}(n-1)\,2^{\,n-2}$ (при $n=1$ матрица нулевая, $\det=0$).

## 1.6. Наибольший определитель матрицы $6\times 6$ из чисел $-1,0,1$

**Метод:** полный перебор невозможен ($3^{36}$ вариантов), поэтому используется локальный поиск (координатный подъём): многократные случайные старты, на каждом шаге для случайной ячейки перебираем 3 значения $\{-1,0,1\}$ и оставляем то, что увеличивает $|\det|$, пока результат не стабилизируется.

In [6]:
import numpy as np  # NumPy для быстрых численных вычислений определителя

rng = np.random.default_rng(0)  # генератор случайных чисел с фиксированным seed для воспроизводимости

def local_search(M, iters=500):  # координатный подъём: пошагово улучшаем матрицу M
    M = M.copy()
    d = abs(round(np.linalg.det(M)))  # текущий (целочисленный) определитель матрицы
    for _ in range(iters):
        i, j = rng.integers(0, 6), rng.integers(0, 6)  # выбираем случайную ячейку матрицы
        old = M[i, j]
        best_val, best_choice = d, old
        for choice in (-1, 0, 1):  # перебираем все три допустимых значения этой ячейки
            if choice == old:
                continue
            M[i, j] = choice
            nd = abs(round(np.linalg.det(M)))
            if nd > best_val:  # запоминаем значение, которое увеличивает |det|
                best_val, best_choice = nd, choice
        M[i, j] = best_choice  # фиксируем лучший найденный выбор для этой ячейки
        d = best_val
    return M, d

best, best_M = 0, None
for _ in range(300):  # делаем много случайных рестартов, чтобы не застрять в локальном максимуме
    M0 = rng.integers(-1, 2, size=(6, 6)).astype(float)  # случайная стартовая матрица из {-1,0,1}
    M, d = local_search(M0)
    if d > best:  # запоминаем лучший результат среди всех рестартов
        best, best_M = d, M.copy()

print("Наибольший найденный определитель:", best)
print(best_M)

Наибольший найденный определитель: 160
[[-1.  1. -1. -1. -1. -1.]
 [-1. -1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1.  1.]
 [-1.  1. -1.  1.  1. -1.]
 [ 1.  1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.]]


**Ответ:** $\det_{\max}=160$, достигается на матрице без нулей (обычная $\pm1$-матрица). Это согласуется с известной последовательностью максимальных определителей для $\{-1,1\}$-матриц при $n=6$ (OEIS A003432) — добавление нулей определитель только уменьшает.

## 1.7. Матрица $80000\times 80000$: почти диагональная

**Метод:** диагональ — арифметическая прогрессия от $0{,}99$ до $1{,}01$; вне диагонали только $a_{1,2}=0{,}57$, $a_{2,1}=0{,}03$. Определитель считается по формуле для матрицы вида "диагональ + возмущение $2\times2$ блока":
$$\det A = \Big(\textstyle\prod_i d_i\Big)\cdot\Big(1-\frac{a_{12}a_{21}}{d_1 d_2}\Big).$$
След обратной матрицы: $\operatorname{tr}(A^{-1})=\sum_i \frac1{d_i}$ с поправкой на изменённый $2\times2$ блок (обратный к блоку $\begin{pmatrix}d_1&a_{12}\\a_{21}&d_2\end{pmatrix}$ вместо $1/d_1,1/d_2$).

In [7]:
import numpy as np  # NumPy для численных расчётов с большими массивами

n = 80000
d1, dn = 0.99, 1.01
d = np.linspace(d1, dn, n)  # диагональ матрицы — арифметическая прогрессия от d1 до dn
a12, a21 = 0.57, 0.03  # единственные два ненулевых внедиагональных элемента

prod_rest = np.exp(np.sum(np.log(np.abs(d[2:])))) * np.prod(np.sign(d[2:]))  # произведение d_3..d_n через сумму логарифмов — устойчиво при больших n
det_A = prod_rest * (d[0]*d[1] - a12*a21)  # определитель = произведение диагонали, скорректированное на возмущённый 2x2 блок

det_block = d[0]*d[1] - a12*a21  # определитель левого верхнего 2x2 блока
inv_block_trace = (d[1] + d[0]) / det_block  # след обратного к этому блоку
trace_inv = inv_block_trace + np.sum(1.0/d[2:])  # след обратной матрицы = вклад блока + сумма 1/d_i по остальным

print("det(A) =", det_A)
print("tr(A^-1) =", trace_inv)

det(A) = 0.258979113865239
tr(A^-1) = 80002.702766086


**Ответ:** 1) $\det A \approx 0{,}259$; 2) $\operatorname{tr}(A^{-1})\approx 80002{,}703$ (совпадает с ответом в условии).

## 1.8. Матрица $43000\times 43000$: диагональ + первая строка

**Метод:** диагональ — геометрическая прогрессия от $1$ до $1{,}07$; первая строка (кроме $a_{1,1}$) — арифметическая прогрессия, оканчивающаяся $a_{1,n}=1{,}10$; остальные внедиагональные элементы нулевые. Такая матрица — верхнетреугольная с "окаймлением" по первой строке, обратную можно построить явной формулой, не обращая матрицу целиком.

Для матрицы $A=D+e_1 r^T-d_1e_1e_1^T$ (где $D=\mathrm{diag}(d_1,\dots,d_n)$, $r$ — первая строка без диагонального элемента) проще и надёжнее — построить обратную матрицу $B=A^{-1}$ явными формулами, зная, что у $A$ (и, как следствие, у $B$) отличны от нуля только диагональ и первая строка.

In [8]:
import numpy as np  # NumPy: работаем только с одномерными массивами длины n, а не с полной матрицей

n = 43000
q = (1.07) ** (1.0/(n-1))  # знаменатель геометрической прогрессии диагонали
diag = 1.0 * q**np.arange(n)  # диагональ: a_11 = 1, ..., a_nn = 1.07

a1n = 1.10
row1 = np.linspace(diag[0], a1n, n)  # первая строка — арифметическая прогрессия до a_{1,n} = 1.10
row1[0] = diag[0]  # первый элемент строки совпадает с диагональным элементом

diag_inv = np.empty(n)
diag_inv[1:] = 1.0/diag[1:]  # диагональ обратной матрицы B при i>0: B[i,i] = 1/diag[i]
diag_inv[0] = 1.0/row1[0]  # угловой элемент B[0,0] = 1/row1[0]

first_row_rest = -(row1[1:]/row1[0]) * diag_inv[1:]  # остальные элементы первой строки B по явной формуле

min_elem = min(diag_inv.min(), first_row_rest.min())  # наименьший элемент B среди диагонали и первой строки
sum_elem = diag_inv.sum() + first_row_rest.sum()  # сумма всех элементов B (остальные элементы нулевые)

print("наименьший элемент B:", min_elem)
print("сумма элементов B:", sum_elem)

наименьший элемент B: -1.0280373831790015
сумма элементов B: -2054.438267010555


**Ответ:** 1) наименьший элемент $B\approx -1{,}028$; 2) сумма элементов $B\approx -2054{,}4$ (совпадает с ответом в условии).

## 1.9. Суммы степеней матрицы $A=\gamma\begin{pmatrix}7&14\\9&1\end{pmatrix}$, $\gamma=0{,}057$

**Метод:** $S_{m,n}=\sum_{i=m}^n A^i$ и $B_m=(I-A)^{-1}A^m$ считаются прямым суммированием степеней матрицы (все собственные значения $A$ по модулю $<1$, ряд сходится). Пункт 3 — подбор наименьшего $k$ перебором по $n$ с условием на максимальный элемент $S_{k,n}$.

In [9]:
import numpy as np  # NumPy для степеней матрицы и обращения

gamma = 0.057
A = gamma * np.array([[7., 14.], [9., 1.]])  # исходная матрица A
I = np.eye(2)

def S(m, n):  # прямая сумма степеней A^m + A^(m+1) + ... + A^n
    total = np.zeros((2, 2))
    P = np.linalg.matrix_power(A, m)
    for i in range(m, n+1):
        total += P
        P = P @ A
    return total

S470 = S(4, 70)  # считаем сумму S_4,70 напрямую суммированием степеней
print("1) max(S_4,70) =", S470.max())

B4 = np.linalg.inv(I - A) @ np.linalg.matrix_power(A, 4)  # B_m = (I-A)^{-1} A^m — сумма бесконечного "хвоста" ряда
print("2) max(B_4) =", B4.max())

def max_S_limit(k):  # предел S_{k,n} при n -> бесконечность равен (I-A)^{-1} A^k
    return (np.linalg.inv(I - A) @ np.linalg.matrix_power(A, k)).max()

k = 0
while max_S_limit(k) >= 0.0002:  # увеличиваем k, пока предел не станет меньше порога 0.0002
    k += 1
print("3) k =", k, " max_S_limit(k) =", max_S_limit(k))

1) max(S_4,70) = 3.609679030803461
2) max(B_4) = 3.611174678109661
3) k = 89  max_S_limit(k) = 0.00018463313242943322


**Ответ:** 1) $\max S_{4,70}\approx 3{,}609679$; 2) $\max B_4\approx 3{,}611175$; 3) $k=89$ (совпадает с ответом в условии).

## 1.10. Определитель матрицы с параметром $x$

$$M=\begin{pmatrix}7&5&5&x\\2&2&6&9\\3&x&8&0\\3&1&1&0\end{pmatrix}$$

**Метод:** символьное вычисление $\det M$ и разложение по степеням $x$ (`Poly`).

In [10]:
from sympy import Matrix, symbols, expand, Poly  # SymPy для символьного (точного) вычисления определителя

x = symbols('x')  # x — параметр матрицы, а не конкретное число
M = Matrix([[7,5,5,x],[2,2,6,9],[3,x,8,0],[3,1,1,0]])  # матрица M(x) из условия

d = expand(M.det())  # вычисляем определитель и раскрываем его в явный многочлен от x
print(d)
Poly(d, x).all_coeffs()  # выделяем коэффициенты [a, b, c] многочлена ax^2+bx+c

16*x**2 - 116*x + 576


**Ответ:** $\det M = 16x^2-116x+576$ ⇒ **1)** $a=16$; **2)** $b=-116$.

## 1.11. Матрица биномиальных коэффициентов по модулю 2 ($n=100$)

**Метод:** строим нижнетреугольную матрицу $C_{i}^{j}\bmod 2$ и рисуем её (синий = 1, жёлтый = 0). По теореме Куммера/Лукаса получившийся узор — фрактал (треугольник Серпинского).

In [11]:
import numpy as np  # для хранения матрицы 100x100
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # для визуализации результата
from math import comb  # для вычисления биномиальных коэффициентов

n = 100
Mbin = np.zeros((n, n), dtype=int)
for i in range(1, n+1):
    for j in range(1, i+1):
        Mbin[i-1, j-1] = comb(i, j) % 2  # заполняем матрицу значениями C_i^j mod 2

fig, ax = plt.subplots(figsize=(5,5))
cmap = matplotlib.colors.ListedColormap(['#f5c451', '#2b4a8f'])  # жёлтый цвет для 0, синий для 1 (как в условии)
ax.imshow(Mbin, cmap=cmap, vmin=0, vmax=1)  # рисуем матрицу как картинку
ax.set_title("Биномиальные коэффициенты mod 2, n=100")
plt.savefig('binom_mod2.png', dpi=110, bbox_inches='tight')
plt.show()

**Ответ:** получившийся узор — фрактал Серпинского (см. рисунок), что и приведено в условии как эталонный ответ.

## 1.12. Матрица Адамара

**а)** $H_1=(1)$, $\displaystyle H_2=\begin{pmatrix}1&1\\1&-1\end{pmatrix}$, $\displaystyle H_4=\begin{pmatrix}1&1&1&1\\1&-1&1&-1\\1&1&-1&-1\\1&-1&-1&1\end{pmatrix}$ (стандартная сильвестровская конструкция $H_{2n}=\begin{pmatrix}H_n&H_n\\H_n&-H_n\end{pmatrix}$).

**б)** Проверяем $H_4=H_2\otimes H_2$ прямым вычислением (произведение Кронекера).

**в)** Аналогично по индукции: если $H_{2^{k-1}}$ построена по той же сильвестровской рекурсии, то по определению $H_{2^k}=\begin{pmatrix}H_{2^{k-1}}&H_{2^{k-1}}\\H_{2^{k-1}}&-H_{2^{k-1}}\end{pmatrix}=H_2\otimes H_{2^{k-1}}$ — это прямое следствие определения произведения Кронекера $A\otimes B$ для $A=H_2=\begin{pmatrix}1&1\\1&-1\end{pmatrix}$.

**г)** Строим $H_{64}=H_2^{\otimes 6}$ и рисуем (оранжевый = $+1$, синий = $-1$).

In [12]:
import numpy as np  # NumPy: np.kron реализует произведение Кронекера

H2 = np.array([[1,1],[1,-1]])  # базовая матрица Адамара H2
H4 = np.kron(H2, H2)  # H4 = H2 ⊗ H2 по сильвестровской конструкции

print("H4 = H2 ⊗ H2 (должна совпасть с заданной в условии матрицей Сильвестра):")
print(H4)

print("H4 H4^T =\n", H4 @ H4.T)  # проверяем определяющее свойство матрицы Адамара: H*H^T = n*I

H4 = H2 ⊗ H2 (должна совпасть с заданной в условии матрицей Сильвестра):
[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
H4 H4^T =
 [[4 0 0 0]
 [0 4 0 0]
 [0 0 4 0]
 [0 0 0 4]]


In [13]:
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # для визуализации H64

H2 = np.array([[1,1],[1,-1]])

def sylvester_hadamard(k):  # рекурсивно строим H_{2^k} = H2 ⊗ H_{2^(k-1)}
    H = np.array([[1]])
    for _ in range(k):
        H = np.kron(H2, H)  # на каждом шаге применяем произведение Кронекера
    return H

H64 = sylvester_hadamard(6)  # получаем матрицу Адамара размера n = 2^6 = 64
print(H64.shape, "проверка ортогональности H*H^T = n*I:", np.allclose(H64 @ H64.T, 64*np.eye(64)))

fig, ax = plt.subplots(figsize=(5,5))
cmap = matplotlib.colors.ListedColormap(['#2b4a8f', '#e8791a'])  # синий цвет для -1, оранжевый для +1
ax.imshow(H64, cmap=cmap, vmin=-1, vmax=1)  # рисуем матрицу как картинку
ax.set_title("Матрица Адамара H_64 = H2^{⊗6}")
plt.savefig('hadamard_64.png', dpi=110, bbox_inches='tight')
plt.show()

(64, 64) проверка ортогональности H*H^T = n*I: True


**Ответ:** равенства проверены прямым вычислением ($H_4=H_2\otimes H_2$, $H_4H_4^T=4I$), $H_{64}$ ортогональна ($H_{64}H_{64}^T=64I$), картинка — шахматно-фрактальный узор, как в условии (с точностью до перестановки строк/столбцов).

## 1.13. Собственное значение с наибольшей мнимой частью

$$A=\begin{pmatrix}14&10&21\\12&15&26\\18&11&27\end{pmatrix}$$

**Метод:** находим характеристический многочлен и его корни (`charpoly`, `solve`), затем — собственный вектор для комплексного $Z$ с $\operatorname{Im}Z>0$, нормированный так, чтобы первая координата равнялась 1.

In [14]:
from sympy import Matrix, symbols  # для точного характеристического многочлена
import numpy as np  # для численного поиска комплексных корней и векторов

A = Matrix([[14,10,21],[12,15,26],[18,11,27]])
x = symbols('x')
cp = A.charpoly(x).as_expr()  # характеристический многочлен матрицы A
print("характеристический многочлен:", cp)

An = np.array(A.tolist(), dtype=complex)  # переводим матрицу в NumPy с комплексным типом данных
w, v = np.linalg.eig(An)  # находим все собственные значения и собственные векторы
print("собственные значения:", w)

idx = np.argmax(w.imag)  # выбираем индекс собственного значения с наибольшей мнимой частью
Z = w[idx]
vec = v[:, idx]
vec_norm = vec / vec[0]  # нормируем вектор так, чтобы первая координата была равна 1
print("Z =", Z)
print("вектор X = (1, U, V) =", vec_norm)

характеристический многочлен: x**3 - 56*x**2 + 209*x - 208
собственные значения: [52.06231934+2.22044605e-16j  1.96884033+3.44789348e-01j
  1.96884033-3.44789348e-01j]
Z = (1.96884033080165+0.344789348427175j)
вектор X = (1, U, V) = [ 1.        +0.j          3.74781973+1.33084677j -2.35758843-0.61731802j]


**Ответ:** $Z\approx 1{,}968840+0{,}344789\,i$, $X=(1,\,U,\,V)$ с $U\approx3{,}747820+1{,}330847\,i$.

**1)** $\operatorname{Im}Z\approx 0{,}344789$; **2)** $\operatorname{Re}U\approx 3{,}747820$.

## 1.14. Минимальный многочлен матрицы $7\times7$

**Метод:** характеристический многочлен даёт возможные корни минимального многочлена и максимально возможные кратности; фактическую (наименьшую) кратность каждого корня в минимальном многочлене определяет **размер наибольшей жордановой клетки** для этого собственного значения — находим её через `jordan_form`, затем проверяем прямой подстановкой, что $A^a(A-I)^b=0$ для найденных степеней, а для меньших степеней — не ноль.

In [15]:
from sympy import Matrix, symbols, factor  # SymPy для точных символьных вычислений без ошибок округления

A = Matrix([
[-3,7,-6,-1,8,-3,-2],
[1,-5,8,-3,-5,4,-5],
[1,3,-4,6,-2,0,8],
[-1,11,-12,9,3,-3,9],
[-3,11,-12,5,8,-4,6],
[-3,2,1,-4,4,1,-7],
[1,-5,6,-2,-4,3,-2]])

x = symbols('x')
print("хар. многочлен:", factor(A.charpoly(x).as_expr()))  # находим характеристический многочлен и раскладываем его на множители

P, J = A.jordan_form()  # жорданова форма показывает размер каждой жордановой клетки
J  # размер клетки для λ задаёт степень множителя (x-λ) в минимальном многочлене

хар. многочлен: x**3*(x - 1)**4


⎡0  1  0  0  0  0  0⎤
⎢                   ⎥
⎢0  0  1  0  0  0  0⎥
⎢                   ⎥
⎢0  0  0  0  0  0  0⎥
⎢                   ⎥
⎢0  0  0  1  1  0  0⎥
⎢                   ⎥
⎢0  0  0  0  1  0  0⎥
⎢                   ⎥
⎢0  0  0  0  0  1  1⎥
⎢                   ⎥
⎣0  0  0  0  0  0  1⎦

In [16]:
from sympy import eye, zeros  # для единичной и нулевой матрицы при проверке

I = eye(7)
print("A^3 (A-I)^2 == 0 ?", A**3*(A-I)**2 == zeros(7,7))  # проверяем гипотезу о минимальном многочлене x^3(x-1)^2
print("A^2 (A-I)^2 == 0 ?", A**2*(A-I)**2 == zeros(7,7))  # убеждаемся, что степень 2 для нуля недостаточна
print("A^3 (A-I)^1 == 0 ?", A**3*(A-I)**1 == zeros(7,7))  # убеждаемся, что степень 1 для единицы недостаточна

A^3 (A-I)^2 == 0 ? True
A^2 (A-I)^2 == 0 ? False
A^3 (A-I)^1 == 0 ? False


Жорданова форма: для $\lambda=0$ — одна клетка размера 3; для $\lambda=1$ — две клетки размера 2. Значит, минимальная степень, аннулирующая матрицу, — $x^3(x-1)^2$; проверка подтверждает, что меньшие степени не дают нуль.

**Ответ:** $\mu_A(x)=x^3(x-1)^2=x^5-2x^4+x^3$.

## 1.15. Собственный ортонормированный базис самосопряжённого оператора

$$A=\begin{pmatrix}17&-8&4\\-8&17&-4\\4&-4&11\end{pmatrix}$$

**Метод:** $A$ симметрична ⇒ собственные векторы для разных $\lambda$ автоматически ортогональны, а внутри собственного подпространства (при кратном $\lambda$) применяем процесс Грама–Шмидта (`GramSchmidt(..., orthonormal=True)`).

In [17]:
from sympy import Matrix  # SymPy для точных вычислений собственных векторов

A = Matrix([[17,-8,4],[-8,17,-4],[4,-4,11]])
print("симметрична:", A.is_symmetric())  # проверяем, что оператор самосопряжён

eigs = A.eigenvects()  # находим собственные значения и собственные векторы матрицы
for val, mult, vecs in eigs:
    print("lambda =", val, " mult =", mult, " векторы:", [v.T for v in vecs])  # печатаем λ, его кратность и базис подпространства

симметрична:

 True
lambda = 9  mult = 2  векторы: [Matrix([[1, 1, 0]]), Matrix([[-1/2, 0, 1]])]
lambda = 27  mult = 1  векторы: [Matrix([[2, -2, 1]])]


In [18]:
from sympy import GramSchmidt, simplify  # GramSchmidt ортонормирует набор векторов

v1 = Matrix([1,1,0])     # собственный вектор для lambda=9
v2 = Matrix([-1,0,2])    # ещё один собственный вектор для lambda=9 (не ортогонален v1)
v3 = Matrix([2,-2,1])    # собственный вектор для lambda=27

basis = GramSchmidt([v1,v2,v3], orthonormal=True)  # ортогонализируем и нормируем все три вектора сразу
for b in basis:
    print(simplify(b.T))

P = Matrix.hstack(*basis)  # собираем новый базис в матрицу перехода P (по столбцам)
simplify(P.T*A*P)  # проверяем: в новом базисе матрица оператора должна стать диагональной

Matrix([[sqrt(2)/2, sqrt(2)/2, 0]])
Matrix([[-sqrt(2)/6, sqrt(2)/6, 2*sqrt(2)/3]])
Matrix([[2/3, -2/3, 1/3]])


⎡9  0  0 ⎤
⎢        ⎥
⎢0  9  0 ⎥
⎢        ⎥
⎣0  0  27⎦

**Ответ:** собственные значения $\lambda_1=\lambda_2=9$, $\lambda_3=27$. Ортонормированный базис:
$$e_1=\Big(\tfrac{\sqrt2}{2},\tfrac{\sqrt2}{2},0\Big),\quad e_2=\Big(-\tfrac{\sqrt2}{6},\tfrac{\sqrt2}{6},\tfrac{2\sqrt2}{3}\Big),\quad e_3=\Big(\tfrac23,-\tfrac23,\tfrac13\Big)$$
Матрица оператора в этом базисе: $\mathrm{diag}(9,9,27)$.

## 1.16. Приведение квадратичной формы к главным осям

$$f(x_1,x_2,x_3,x_4)=3x_1^2+8x_1x_2-3x_2^2+4x_3^2-4x_3x_4+x_4^2$$

**Метод:** записываем симметричную матрицу формы (она блочно-диагональна: блок $\{x_1,x_2\}$ и блок $\{x_3,x_4\}$), диагонализируем ортогонально (`diagonalize(normalize=True)`), проверяем ортогональность $P^TP=I$.

In [19]:
from sympy import Matrix, pprint, simplify  # SymPy для ортогональной диагонализации

Q = Matrix([[3,4,0,0],[4,-3,0,0],[0,0,4,-2],[0,0,-2,1]])  # симметричная матрица квадратичной формы
P, D = Q.diagonalize(normalize=True)  # находим матрицу перехода P и диагональную матрицу D сразу

print("D ="); pprint(D)
print("P ="); pprint(P)
print("P^T P = I ?"); pprint(simplify(P.T*P))  # проверяем, что P действительно ортогональна

D =
⎡-5  0  0  0⎤
⎢           ⎥
⎢0   0  0  0⎥
⎢           ⎥
⎢0   0  5  0⎥
⎢           ⎥
⎣0   0  0  5⎦
P =
⎡-√5         2⋅√5        ⎤
⎢────   0    ────    0   ⎥
⎢ 5           5          ⎥
⎢                        ⎥
⎢2⋅√5         √5         ⎥
⎢────   0     ──     0   ⎥
⎢ 5           5          ⎥
⎢                        ⎥
⎢       √5         -2⋅√5 ⎥
⎢ 0     ──    0    ──────⎥
⎢       5            5   ⎥
⎢                        ⎥
⎢      2⋅√5          √5  ⎥
⎢ 0    ────   0      ──  ⎥
⎣       5            5   ⎦
P^T P = I ?
⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦


**Ответ:** ортогональное преобразование $x=Py$ с
$$x_1=\tfrac{2y_1+y_2}{\sqrt5},\ x_2=\tfrac{y_1-2y_2}{\sqrt5},\qquad x_3=\tfrac{-2y_3+y_4}{\sqrt5},\ x_4=\tfrac{y_3+2y_4}{\sqrt5}$$
приводит форму к каноническому виду
$$f=5y_1^2-5y_2^2+5y_3^2+0\cdot y_4^2.$$

## 1.17. Классификация кривых второго порядка

**Метод:** для $Ax^2+Bxy+Cy^2+Dx+Ey+F=0$ строим матрицу квадратичной части $Q=\begin{pmatrix}A&B/2\\B/2&C\end{pmatrix}$ и полную матрицу $3\times3$. Знак $\delta=\det Q$ определяет тип (эллипс/гипербола/парабола), $\Delta=\det$ полной матрицы — невырожденность. Находим центр (решая $\nabla=0$), значение $F$ в центре и координаты канонической системы — из собственных векторов $Q$ (угол поворота).

In [20]:
from sympy import Matrix, Rational, symbols, Eq, solve, simplify  # SymPy для точных инвариантов кривой

def analyze_conic(A, B, C, D, E, F, label):
    print(f"=== {label} ===")
    Q = Matrix([[A, Rational(B,2)], [Rational(B,2), C]])  # матрица квадратичной части кривой
    full = Matrix([[A, Rational(B,2), Rational(D,2)],
                   [Rational(B,2), C, Rational(E,2)],
                   [Rational(D,2), Rational(E,2), F]])  # полная матрица кривой 3x3
    print("delta =", Q.det(), "   Delta =", full.det())  # delta задаёт тип кривой, Delta — её невырожденность

    for val, mult, vecs in Q.eigenvects():  # собственные векторы Q задают направления главных осей
        v = vecs[0]
        vn = (v / v.norm())
        print(f"  lambda={val}, собств. вектор (норм.) = {vn.T}")

    x, y = symbols('x y')
    sol = solve([Eq(2*A*x + B*y + D, 0), Eq(B*x + 2*C*y + E, 0)], [x, y])  # центр — решение системы "градиент = 0"
    x0, y0 = sol[x], sol[y]
    Fc = A*x0**2 + B*x0*y0 + C*y0**2 + D*x0 + E*y0 + F  # значение F в центре нужно для канонического уравнения
    print("  центр:", sol, "  F(центр) =", simplify(Fc))
    print()

analyze_conic(5, 4, 8, -32, -56, 80, "a) 5x^2+4xy+8y^2-32x-56y+80=0")  # анализируем первую кривую
analyze_conic(5, 12, 0, -22, -12, -19, "b) 5x^2+12xy-22x-12y-19=0")  # анализируем вторую кривую

=== a) 5x^2+4xy+8y^2-32x-56y+80=0 ===
delta = 36    Delta = -1296
  lambda=4, собств. вектор (норм.) = Matrix([[-2*sqrt(5)/5, sqrt(5)/5]])
  lambda=9, собств. вектор (норм.) = Matrix([[sqrt(5)/5, 2*sqrt(5)/5]])


  центр: {x: 2, y: 3}   F(центр) = -36

=== b) 5x^2+12xy-22x-12y-19=0 ===
delta = -36    Delta = 1296
  lambda=-4, собств. вектор (норм.) = Matrix([[-2*sqrt(13)/13, 3*sqrt(13)/13]])
  lambda=9, собств. вектор (норм.) = Matrix([[3*sqrt(13)/13, 2*sqrt(13)/13]])
  центр: {x: 1, y: 1}   F(центр) = -36



**Ответ а):** $\delta=36>0$ — эллипс. Центр $(2,3)$, собственные значения $4,9$ (оси под углом $\approx63{,}43^\circ$ и $\approx153{,}43^\circ$ к Ox). Каноническое уравнение:
$$4X^2+9Y^2=36\ \Longleftrightarrow\ \frac{X^2}{9}+\frac{Y^2}{4}=1\quad(a=3,\,b=2)$$

**Ответ б):** $\delta=-36<0$ — гипербола. Центр $(1,1)$, собственные значения $9,-4$ (оси под углом $\approx33{,}69^\circ$ и $\approx123{,}69^\circ$). Каноническое уравнение:
$$9X^2-4Y^2=36\ \Longleftrightarrow\ \frac{X^2}{4}-\frac{Y^2}{9}=1\quad(a=2,\,b=3)$$

## 1.18. Положительная определённость $Q(x_1,x_2,x_3)=x_1^2+4x_2^2+x_3^2+2\lambda x_1x_2+10x_1x_3+6x_2x_3$

**Метод:** критерий Сильвестра — все угловые миноры матрицы формы должны быть положительны. Строим матрицу с параметром $\lambda$ и решаем неравенства $M_1>0,\,M_2>0,\,M_3>0$.

In [21]:
from sympy import symbols, Matrix, expand, solve  # SymPy для символьных неравенств с параметром

lam = symbols('lambda', real=True)  # λ — вещественный параметр
M = Matrix([[1, lam, 5], [lam, 4, 3], [5, 3, 1]])  # матрица квадратичной формы

M1, M2, M3 = M[0,0], M[:2,:2].det(), M.det()  # три угловых минора по критерию Сильвестра
print("M1 =", M1)
print("M2 =", M2, " => ", solve(M2 > 0, lam))  # решаем неравенство M2 > 0 относительно λ
print("M3 =", expand(M3), " => ", solve(M3 > 0, lam))  # решаем неравенство M3 > 0 относительно λ

M1 = 1
M2 = 4 - lambda**2  =>  (-2 < lambda) & (lambda < 2)
M3 = -lambda**2 + 30*lambda - 105  =>  (lambda < 2*sqrt(30) + 15) & (15 - 2*sqrt(30) < lambda)


$M_2>0 \Rightarrow -2<\lambda<2$, а $M_3>0 \Rightarrow 15-2\sqrt{30}<\lambda<15+2\sqrt{30}$ (т.е. примерно $4{,}05<\lambda<25{,}95$). Пересечение этих двух интервалов пусто.

**Ответ:** ни при каком вещественном $\lambda$ форма $Q$ не является положительно определённой.

## 1.19. Отрицательная определённость $Q(x_1,x_2,x_3)=\lambda x_1^2-2x_2^2-3x_3^2+2x_1x_2-2x_1x_3+2x_2x_3$

**Метод:** критерий Сильвестра для отрицательной определённости — знаки угловых миноров чередуются, начиная с минуса: $M_1<0,\,M_2>0,\,M_3<0$.

In [22]:
from sympy import symbols, Matrix, expand, solve  # SymPy для символьных неравенств с параметром

lam = symbols('lambda', real=True)
M = Matrix([[lam,1,-1], [1,-2,1], [-1,1,-3]])  # матрица квадратичной формы

M1, M2, M3 = M[0,0], M[:2,:2].det(), M.det()  # три угловых минора
print("M1 =", M1, " => ", solve(M1 < 0, lam))  # для отрицательной определённости первый минор должен быть < 0
print("M2 =", M2, " => ", solve(M2 > 0, lam))  # второй минор должен быть > 0
print("M3 =", expand(M3), " => ", solve(M3 < 0, lam))  # третий минор снова должен быть < 0

M1 = lambda  =>  lambda < 0
M2 = -2*lambda - 1  =>  lambda < -1/2
M3 = 5*lambda + 3  =>  lambda < -3/5


Условия: $\lambda<0$, $\lambda<-\tfrac12$, $\lambda<-\tfrac35$. Самое сильное ограничение — последнее.

**Ответ:** $\lambda<-\dfrac35$.

## 1.20. Эквивалентность квадратичных форм над $\mathbb R$

$$Q_1=2x_1^2+9x_2^2+3x_3^2+8x_1x_2-4x_1x_3-10x_2x_3,\qquad Q_2=2x_1^2+3x_2^2+6x_3^2-4x_1x_2-4x_1x_3+8x_2x_3$$

**Метод (закон инерции Сильвестра):** две вещественные квадратичные формы эквивалентны над $\mathbb R$ тогда и только тогда, когда у них совпадают ранг и сигнатура (число положительных / отрицательных собственных значений матрицы формы). Считаем ранги и спектры обеих матриц.

In [23]:
from sympy import Matrix  # для точного вычисления ранга матрицы
import numpy as np  # для численного спектра (eigvalsh — для симметричных матриц)

Q1 = Matrix([[2,4,-2],[4,9,-5],[-2,-5,3]])
Q2 = Matrix([[2,-2,-2],[-2,3,4],[-2,4,6]])

print("rank Q1 =", Q1.rank(), "  rank Q2 =", Q2.rank())  # сравниваем ранги обеих форм

w1 = np.linalg.eigvalsh(np.array(Q1.tolist(), dtype=float))  # спектр Q1 (знаки собственных значений — сигнатура)
w2 = np.linalg.eigvalsh(np.array(Q2.tolist(), dtype=float))  # спектр Q2
print("спектр Q1:", w1)
print("спектр Q2:", w2)

rank Q1 = 2   rank Q2 = 2
спектр Q1: [-2.19025837e-16  4.42561476e-01  1.35574385e+01]
спектр Q2: [-3.53542501e-16  1.22799813e+00  9.77200187e+00]


Обе матрицы имеют ранг 2 и сигнатуру $(2\text{ полож.},\,0\text{ отриц.},\,1\text{ нулевое с.з.})$.

**Ответ:** да, $Q_1$ и $Q_2$ эквивалентны над $\mathbb R$ — обе приводятся к каноническому виду $5y_1^2+\varepsilon y_2^2$ (два положительных коэффициента, один нулевой).